### ISSUE TITLE
index wikipedia using local copy get clojure.lang.ExceptionInfo: throw+:

### ISSUE THREAD

**Issue by heyuze** [elastic/stream2es#54]
java version "1.8.0_51"
elasticsearch-2.0.0

I used the command

    ./stream2es wiki --source enwiki-20151102-pages-articles-multistream.xml.bz2 

but got

    clojure.lang.ExceptionInfo: throw+: {:type :stream2es.http/urlparse} {:object {:type :stream2es.http/urlparse}, :environment {u "enwiki-20151102-pages-articles-multistream.xml.bz2", o__5349__auto__ {:type :stream2es.http/urlparse}}}
        at stream2es.http$make_jurl.invoke(http.clj:48)
        at stream2es.http$make_target.invoke(http.clj:78)
        at stream2es.http$make_target.invoke(http.clj:76)
        at stream2es.stream.wiki$fn__6629.invoke(wiki.clj:42)
        at stream2es.stream$fn__5804$G__5797__5811.invoke(stream.clj:22)
        at stream2es.bootstrap$boot.invoke(bootstrap.clj:70)
        at stream2es.main$_main.doInvoke(main.clj:339)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at stream2es.main.main(Unknown Source)

**Comment by drewr** [comment]
It expects a URI-style string (`file:///path/to/bz2`, or just `/path/to/bz2`).
