### ISSUE TITLE
partial data imported

### ISSUE THREAD

**Issue by shantanuo** [elastic/stream2es#62]
Only partial data was imported. I got this error.

# cat file.json | ./stream2es stdin --target "http://localhost:9200/myindex/mytype/"
Exception in thread "stream dispatcher" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('9' (code 57)): was expecting double-quote to start field name
 at [Source: java.io.StringReader@66fd845; line: 1, column: 35]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1701)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:642)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:63)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:61)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:63)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:61)
        at cheshire.parse$parse.invokeStatic(parse.clj:98)
        at cheshire.parse$parse.invoke(parse.clj:86)
        at cheshire.core$parse_string.invokeStatic(core.clj:205)
        at cheshire.core$parse_string.invoke(core.clj:191)
        at cheshire.core$parse_string.invokeStatic(core.clj:202)
        at cheshire.core$parse_string.invoke(core.clj:191)
        at stream2es.stream.stdin$fn__6955.invokeStatic(stdin.clj:52)
        at stream2es.stream.stdin$fn__6955.invoke(stdin.clj:49)
        at stream2es.stream$fn__6530$G__6525__6537.invoke(stream.clj:12)
        at stream2es.main$make_object_processor$fn__7305.invoke(main.clj:224)
        at stream2es.main$start_doc_stream$disp__7292.invoke(main.clj:209)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)

^C2016-07-30T14:31:55.131+0000 INFO  20:11.473 85.8d/s 40.9K/s (48.4mb) indexed 103936 streamed 103967 errors 0

**Comment by drewr** [comment]
What's in file.json?  Something in there doesn't seem to be formatted
correctly.
